fn main() {
    #[cfg(windows)]
    {
        // Skip gracefully rather than failing the build: `assets/icon.ico`
        // is generated by `cargo run --example gen_icon`, and that example
        // build also goes through this same build.rs before the file
        // exists on a first checkout.
        if std::path::Path::new("assets/icon.ico").exists() {
            let mut res = winres::WindowsResource::new();
            res.set_icon("assets/icon.ico");
            res.compile()
                .expect("failed to embed assets/icon.ico into the .exe");
        } else {
            println!(
                "cargo:warning=assets/icon.ico not found - run `cargo run --example gen_icon` to generate it, then rebuild to embed it"
            );
        }
    }
}
